### ISSUE TITLE
mpdas 0.4.3 checksum mismatch

### ISSUE THREAD

**Issue by ilovezfs** [hrkfdn/mpdas#41]
URL:
https://www.50hz.ws/mpdas/mpdas-0.4.3.tar.gz

Expected SHA-256: 925089a1d395352c27df68b274b33258a09e334e784322e72dc064241aa2e075

Actual SHA-256:
069e368bde35b2b3bd79439052c863a0f8c3b25ed454b5ab51f84fa6878b674e

The expected checksum is what what we had in Homebrew for the SHA-256 when the formula was upgraded to version 0.4.3 on Mon Jul 3 12:05:54 2017 -0700. See https://github.com/Homebrew/homebrew-core/pull/15256.

But currently downloading the file gives a different checksum.

I wanted to make sure you weren't hacked, and ask what the reason(s) for the changes were.

**Comment by hrkfdn** [comment]
Hey there,

Thanks for contacting me regarding this. No worries, this was intentional.
I had to change something last minute but you were too fast for me ;)

I tried to notify you about this (
https://github.com/Homebrew/homebrew-core/commit/be328e826016bf53eaf1281ab97392ce9ea928fe#diff-6ba26699b4701de3080d0faf8391b62d),
but I guess it didn't go through.

Cheers
Henrik

**Comment by ilovezfs** [comment]
Thanks for confirming the change!
